ASSUME CS:CODE, DS:DATA 
; ASSUME IS AN ASSEMBLER DIRECTIVE TO DECLARE SEGMENTS
DATA SEGMENT
        STR1 DB "COMPUTER SCIENCE AND ENGINEERING", 13,10,"GEETHANJALI",0DH,0AH,"AIML$"
                                ; DISPLAYING MULTIPLE STRING IN NEW LINE
DATA ENDS

CODE SEGMENT
        MOV AX, DATA ; READING THE ADDRESS OF DATA SEGMENT AND MOVING TO AX
        MOV DS, AX ; MOVING THE CONTENTS OF AX TO DS

        MOV DX, OFFSET STR1 ; READING THE OFFSET ADDRESS OF STR1

        MOV AH, 09H  ; DOS INT 21H SERVICE: DISPLAY STRING
        INT 21H  ; THE TWO INSTRUCTION TOGETHER CONSIDERED UNDER ISR-09
                 ; INTERRUT SERVICE ROUTINE 09 TO DISPLAY STRING OF CHARACTERS

        MOV AH, 4CH ; DOS INT 21H SERVICE: TERMINATE WITH RETURN CODE
        INT 21H ; THE TWO INSTRUCTIONS TOGETHER CONSIDERED UNDER ISR-4C
                 ; INTERRUT SERVICE ROUTINE 4C TO TERMINATE WITH RETURN CODE
CODE ENDS
END  ; END OF THE PROGRAM
